#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  echo "usage: $0 <tag>"
  exit 1
fi

AUDIT_ROOT="${2:-}"
PROFILE_ROOT="${3:-}"
WORKFLOW_EXPORT_ROOT="${4:-}"

if [[ -z "$AUDIT_ROOT" ]]; then
  AUDIT_ROOT="$(find "$REPO_ROOT/Docs/archive/reviews/2026-03-28/review_artifacts" -mindepth 1 -maxdepth 1 -type d -name '*finished_branch_audit' | sort | tail -n 1)"
fi

if [[ -z "$PROFILE_ROOT" ]]; then
  PROFILE_ROOT="$(find "$REPO_ROOT/Docs/archive/reviews/2026-03-28/runtime_profiles" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort | tail -n 1 || true)"
fi

BUNDLE_ROOT="$REPO_ROOT/Docs/archive/releases/$TAG"
mkdir -p \
  "$BUNDLE_ROOT/profiling" \
  "$BUNDLE_ROOT/workflow_exports" \
  "$BUNDLE_ROOT/manifests"

cat >"$BUNDLE_ROOT/00_INDEX.md" <<EOF
# Release Bundle Index

Tag: \`$TAG\`
Generated by: \`Tools/docs/generate_release_bundle.sh\`
Archive root: \`$BUNDLE_ROOT\`
Audit root: \`${AUDIT_ROOT:-missing}\`
Profile root: \`${PROFILE_ROOT:-missing}\`

## Contents

- \`RELEASE_APPROVAL.md\`
- \`EXECUTIVE_STATUS.md\`
- \`VALIDATION_SUMMARY.md\`
- lane logs
- workflow exports
- profiling artifacts
- manifest files
EOF

write_note() {
  local path="$1"
  local message="$2"
  cat >"$path" <<EOF
$message
EOF
}

copy_if_exists() {
  local source="$1"
  local destination="$2"
  if [[ -f "$source" ]]; then
    cp "$source" "$destination"
  else
    write_note "$destination" "Missing source artifact: $source"
  fi
}

concat_lane_logs() {
  local destination="$1"
  shift
  : >"$destination"
  for pattern in "$@"; do
    local source
    source="$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name "$pattern" | sort | head -n 1 || true)"
    if [[ -n "$source" ]]; then
      {
        printf '===== %s =====\n' "$source"
        cat "$source"
        printf '\n'
      } >>"$destination"
    fi
  done
}

git rev-parse HEAD > "$BUNDLE_ROOT/manifests/git_head.txt"
printf '%s\n' "$TAG" > "$BUNDLE_ROOT/manifests/git_tag.txt"
xcodebuild -version > "$BUNDLE_ROOT/manifests/xcode_version.txt"
swift --version > "$BUNDLE_ROOT/manifests/swift_version.txt"

cat > "$BUNDLE_ROOT/manifests/package_matrix.txt" <<'EOF'
CloudXModels
DiagnosticsKit
DesignSystemTV
InputBridge
XCloudAPI
StreamingCore
VideoRenderingKit
CloudXCore
EOF

cat > "$BUNDLE_ROOT/manifests/scheme_matrix.txt" <<'EOF'
CloudX-Debug
CloudX-ShellUI
CloudX-Perf
CloudX-MetalProfile
CloudX-ReleaseRun
CloudX-Validation
EOF

if [[ -n "$AUDIT_ROOT" && -d "$AUDIT_ROOT" ]]; then
  if [[ ! -f "$AUDIT_ROOT/04_validation_summary.md" ]]; then
    bash Tools/docs/generate_validation_summary.sh "$AUDIT_ROOT" "$AUDIT_ROOT/04_validation_summary.md"
  fi

  copy_if_exists "$AUDIT_ROOT/04_validation_summary.md" "$BUNDLE_ROOT/VALIDATION_SUMMARY.md"
  concat_lane_logs "$BUNDLE_ROOT/guard_sweep.log" "01_*" "02_*" "03_*" "03a_*" "04_*" "05_*" "06_*" "07_*" "08_*" "09_*" "10_*" "11_*" "12_*" "13_*" "14_*" "15_*" "16_*" "17_*" "18_*" "19_*" "20_*"
  concat_lane_logs "$BUNDLE_ROOT/package_sweep.log" "21_*" "22_*" "23_*" "24_*" "25_*" "26_*" "27_*" "28_*"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '30_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/app_smoke.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '31_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/runtime_safety.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '32_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/shell_ui.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '38a_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/shell_visual_regression.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '35_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/release_run.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '36_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/cloudx_validation.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '37_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/hardware_device.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '38_*Production_Hardening_Checks.log' | sort | head -n 1 || true)" "$BUNDLE_ROOT/production_hardening.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '18_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/docs_truth_sync.log"
  copy_if_exists "$(find "$AUDIT_ROOT/lanes" -maxdepth 1 -type f -name '17_*' | sort | head -n 1 || true)" "$BUNDLE_ROOT/package_platform_audit.log"
else
  write_note "$BUNDLE_ROOT/VALIDATION_SUMMARY.md" "Missing audit root; run generate_release_bundle.sh with an audit directory."
  write_note "$BUNDLE_ROOT/guard_sweep.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/package_sweep.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/app_smoke.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/runtime_safety.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/shell_ui.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/shell_visual_regression.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/release_run.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/cloudx_validation.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/hardware_device.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/production_hardening.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/docs_truth_sync.log" "Missing audit root."
  write_note "$BUNDLE_ROOT/package_platform_audit.log" "Missing audit root."
fi

if [[ -n "$PROFILE_ROOT" && -d "$PROFILE_ROOT" ]]; then
  copy_if_exists "$PROFILE_ROOT/summary.md" "$BUNDLE_ROOT/profiling/summary.md"
  copy_if_exists "$PROFILE_ROOT/time_profiler_hardware.trace" "$BUNDLE_ROOT/profiling/time_profiler_hardware.trace"
  copy_if_exists "$PROFILE_ROOT/swiftui_hardware.trace" "$BUNDLE_ROOT/profiling/swiftui_hardware.trace"
  copy_if_exists "$PROFILE_ROOT/swiftui_hitches.xml" "$BUNDLE_ROOT/profiling/swiftui_hitches.xml"
  copy_if_exists "$PROFILE_ROOT/swiftui_updates.xml" "$BUNDLE_ROOT/profiling/swiftui_updates.xml"
  copy_if_exists "$PROFILE_ROOT/build.log" "$BUNDLE_ROOT/profiling/build.log"
  copy_if_exists "$PROFILE_ROOT/install.log" "$BUNDLE_ROOT/profiling/install.log"
  copy_if_exists "$PROFILE_ROOT/devicectl_launch.json" "$BUNDLE_ROOT/profiling/devicectl_launch.json"
else
  write_note "$BUNDLE_ROOT/profiling/summary.md" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/time_profiler_hardware.trace" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/swiftui_hardware.trace" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/swiftui_hitches.xml" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/swiftui_updates.xml" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/build.log" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/install.log" "Missing profile root."
  write_note "$BUNDLE_ROOT/profiling/devicectl_launch.json" "Missing profile root."
fi

for export_name in \
  ci-pr-fast-guards.txt \
  ci-packages.txt \
  ci-app-build-and-smoke.txt \
  ci-runtime-safety.txt \
  ci-shell-ui.txt \
  ci-shell-visual-regression.txt \
  ci-release-and-validation.txt \
  ci-hardware-device.txt; do
  if [[ -n "$WORKFLOW_EXPORT_ROOT" && -f "$WORKFLOW_EXPORT_ROOT/$export_name" ]]; then
    cp "$WORKFLOW_EXPORT_ROOT/$export_name" "$BUNDLE_ROOT/workflow_exports/$export_name"
  else
    write_note "$BUNDLE_ROOT/workflow_exports/$export_name" "Missing workflow export: $export_name"
  fi
done

python3 - "$BUNDLE_ROOT" "$TAG" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path

bundle_root = Path(sys.argv[1])
tag = sys.argv[2]

git_head = (bundle_root / "manifests" / "git_head.txt").read_text().strip()
validation_summary = bundle_root / "VALIDATION_SUMMARY.md"
profiling_summary = bundle_root / "profiling" / "summary.md"

required_files = [
    bundle_root / "VALIDATION_SUMMARY.md",
    bundle_root / "guard_sweep.log",
    bundle_root / "package_sweep.log",
    bundle_root / "app_smoke.log",
    bundle_root / "runtime_safety.log",
    bundle_root / "shell_ui.log",
    bundle_root / "shell_visual_regression.log",
    bundle_root / "release_run.log",
    bundle_root / "cloudx_validation.log",
    bundle_root / "hardware_device.log",
    bundle_root / "production_hardening.log",
    bundle_root / "docs_truth_sync.log",
    bundle_root / "package_platform_audit.log",
    bundle_root / "profiling" / "summary.md",
]

required_workflow_exports = [
    bundle_root / "workflow_exports" / "ci-pr-fast-guards.txt",
    bundle_root / "workflow_exports" / "ci-packages.txt",
    bundle_root / "workflow_exports" / "ci-app-build-and-smoke.txt",
    bundle_root / "workflow_exports" / "ci-runtime-safety.txt",
    bundle_root / "workflow_exports" / "ci-shell-ui.txt",
    bundle_root / "workflow_exports" / "ci-shell-visual-regression.txt",
    bundle_root / "workflow_exports" / "ci-release-and-validation.txt",
    bundle_root / "workflow_exports" / "ci-hardware-device.txt",
]

placeholder_prefixes = (
    "Missing workflow export:",
    "Missing source artifact:",
    "Missing audit root.",
    "Missing audit root;",
    "Missing profile root.",
)

def is_missing_or_placeholder(path: Path) -> bool:
    if not path.exists():
        return True
    if not path.is_file():
        return False
    try:
        first_line = path.read_text(errors="ignore").splitlines()[0].strip()
    except IndexError:
        first_line = ""
    return any(first_line.startswith(prefix) for prefix in placeholder_prefixes)

missing = [
    str(path.relative_to(bundle_root))
    for path in [*required_files, *required_workflow_exports]
    if is_missing_or_placeholder(path)
]

validation_text = validation_summary.read_text(errors="ignore") if validation_summary.exists() else ""
validation_blocked = "Current posture: not ready for approval" in validation_text

workflow_blockers: list[str] = []
for export_path in required_workflow_exports:
    if not export_path.exists() or not export_path.is_file():
        continue
    text = export_path.read_text(errors="ignore")
    status = None
    conclusion = None
    for line in text.splitlines():
        if line.startswith("status: "):
            status = line.split(": ", 1)[1].strip()
        if line.startswith("conclusion: "):
            conclusion = line.split(": ", 1)[1].strip()
    if status != "completed" or conclusion != "success":
        workflow_blockers.append(
            f"{export_path.name} status={status or 'unknown'} conclusion={conclusion or 'unknown'}"
        )

approval_lines = [
    "# Release Approval",
    "",
    f"- Tag: `{tag}`",
    f"- Git head: `{git_head}`",
    "",
    "## Required Evidence",
    "",
]
if missing:
    approval_lines.append("- Status: incomplete")
    approval_lines.append(f"- Missing artifacts: {', '.join(sorted(missing))}")
elif validation_blocked or workflow_blockers:
    approval_lines.append("- Status: blocked")
    if validation_blocked:
        approval_lines.append("- Validation summary still reports failing required local lanes on this candidate.")
    if workflow_blockers:
        approval_lines.append(f"- Hosted workflow blockers: {'; '.join(workflow_blockers)}")
else:
    approval_lines.append("- Status: approvable-artifact-set")
    approval_lines.append("- Required bundle files are present and the captured workflow exports report completed success states.")

approval_lines.extend(
    [
        "",
        "## Reviewer Notes",
        "",
        "- Confirm all lane logs correspond to the same candidate head.",
        "- Confirm hardware and profiling evidence is current when required.",
        "- Confirm docs still point to this release bundle as the approval evidence source.",
        "",
    ]
)

executive_lines = [
    "# Executive Status",
    "",
    f"- Tag: `{tag}`",
    f"- Git head: `{git_head}`",
    f"- Validation summary: `{validation_summary.name}`",
    f"- Profiling summary: `{profiling_summary.name}`",
    "",
    "## Summary",
    "",
]
if missing:
    executive_lines.append("- Release bundle is not yet approval-ready because required artifacts are still missing.")
elif validation_blocked or workflow_blockers:
    executive_lines.append("- Release bundle is not approval-ready on this candidate because current local or hosted validation is still blocked.")
else:
    executive_lines.append("- Release bundle structure is complete. Final release readiness depends on the contents of the included validation and profiling evidence.")

executive_lines.extend(
    [
        "",
        "## Evidence Paths",
        "",
        "- `VALIDATION_SUMMARY.md`",
        "- `RELEASE_APPROVAL.md`",
        "- `profiling/summary.md`",
        "- `workflow_exports/`",
    ]
)

(bundle_root / "RELEASE_APPROVAL.md").write_text("\n".join(approval_lines) + "\n")
(bundle_root / "EXECUTIVE_STATUS.md").write_text("\n".join(executive_lines) + "\n")
PY

echo "Created release bundle at $BUNDLE_ROOT"
